name: Windows Builds

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-2016, windows-latest]
        node-version: [8.x, 10.x, 11.x, 12.x]
        exclude:
            - os: windows-2016
              node-version: 12.x
            - os: windows-latest
              node-version: 8.x
            - os: windows-latest
              node-version: 10.x
            - os: windows-latest
              node-version: 11.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install

